# Generated by Django 6.0.5 on 2026-06-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='ine',
            field=models.CharField(blank=True, help_text='Identifiant National Étudiant (INE)', max_length=50, null=True, unique=True),
        ),
    ]
