# Generated by Django 6.0.5 on 2026-06-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_etudiant_ine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Administrateur', 'verbose_name_plural': 'Administrateurs'},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='departement',
            field=models.CharField(choices=[('DLSI', 'DLSI'), ('NTIC', 'NTIC')], default='DLSI', max_length=50),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='faculte',
            field=models.CharField(default='CENTRE INFORMATIQUE', max_length=150),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom_nom_mere',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom_pere',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='programme',
            field=models.CharField(default='DEVELOPPEMENT LOGICIEL', max_length=150),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='annee_inscription',
            field=models.CharField(help_text='Exemple: 2023-2024', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('ETUDIANT', 'Étudiant')], default='ETUDIANT', help_text="Le rôle de l'utilisateur définit ses permissions de base dans l'application.", max_length=20),
        ),
    ]
