# Generated by Django 6.0.5 on 2026-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_admin_options_etudiant_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='a_valide_l1',
            field=models.BooleanField(default=False, help_text="L'étudiant a validé toutes les matières de la L1"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='a_valide_l2',
            field=models.BooleanField(default=False, help_text="L'étudiant a validé toutes les matières de la L2"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='a_valide_l3',
            field=models.BooleanField(default=False, help_text="L'étudiant a validé toutes les matières de la L3"),
        ),
    ]
