# Generated by Django 6.0.5 on 2026-05-31 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Nom du type d'attestation", max_length=100, unique=True)),
                ('template_html', models.CharField(help_text='Nom ou chemin du template HTML (ex: inscription.html)', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Type d'attestation",
                'verbose_name_plural': "Types d'attestations",
            },
        ),
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True, help_text="Commentaire de l'agent (obligatoire si rejeté)", null=True)),
                ('admin', models.ForeignKey(blank=True, help_text="L'agent qui a traité la demande", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='authentication.admin')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='authentication.etudiant')),
                ('type_attestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='attestations.typeattestation')),
            ],
            options={
                'verbose_name': "Demande d'attestation",
                'verbose_name_plural': "Demandes d'attestations",
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_fichier', models.FileField(help_text='Le fichier PDF généré', upload_to='attestations/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('taille_ko', models.IntegerField(blank=True, help_text='Taille du fichier en Ko', null=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='attestations.demandeattestation')),
            ],
            options={
                'verbose_name': 'Document PDF',
                'verbose_name_plural': 'Documents PDF',
            },
        ),
    ]
