# Generated by Django 6.0.5 on 2026-05-31 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('current_state', models.CharField(choices=[('INIT', 'Initialisation'), ('AWAITING_AUTH', 'Attente authentification'), ('CHOOSING_TYPE', "Choix du type d'attestation"), ('CONFIRMING_DATA', 'Confirmation des données'), ('GENERATING_PDF', 'Génération du PDF'), ('COMPLETED', 'Terminé'), ('ERROR', 'Erreur')], default='INIT', max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to='authentication.etudiant')),
            ],
            options={
                'verbose_name': 'Session Chatbot',
                'verbose_name_plural': 'Sessions Chatbot',
                'ordering': ['-updated_at'],
            },
        ),
    ]
