# Generated by Django 6.0.5 on 2026-06-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='current_state',
            field=models.CharField(choices=[('ACCUEIL', 'Accueil (Demande Numéro)'), ('ATTENTE_MDP', 'Attente Mot de Passe'), ('AUTHENTIFIE', 'Authentifié (Choix Document)'), ('DOCUMENT_CHOISI', 'Document Choisi'), ('ERROR', 'Erreur')], default='ACCUEIL', max_length=50),
        ),
    ]
